name: Commit Tests

env:
  release_major: 8

on:
  push:

jobs:
  build_llvm:
    name: check-all llvm/clang/pstore
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
    steps:
    - name: Install Ninja
      uses: llvm/actions/install-ninja@main
    - name: Checkout LLVM
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Checkout pstore
      uses: actions/checkout@v2
      with:
        repository: SNSystems/pstore
        path: pstore
    - name: Test LLVM
      uses: llvm/actions/build-test-llvm-project@main
      with:
        cmake_args: -G Ninja -DLLVM_ENABLE_PROJECTS="clang;pstore;rld" -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=OFF -DLLVM_PARALLEL_LINK_JOBS=1
